/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SquadraRouteImport } from './routes/squadra'
import { Route as RegolamentoRouteImport } from './routes/regolamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ClassificaRouteImport } from './routes/classifica'
import { Route as BallottaggioRouteImport } from './routes/ballottaggio'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTeamsRouteImport } from './routes/api/teams'
import { Route as ApiResultsRouteImport } from './routes/api/results'
import { Route as ApiClassificaDataRouteImport } from './routes/api/classifica-data'
import { Route as ApiAdminRouteImport } from './routes/api/admin'

const SquadraRoute = SquadraRouteImport.update({
  id: '/squadra',
  path: '/squadra',
  getParentRoute: () => rootRouteImport,
} as any)
const RegolamentoRoute = RegolamentoRouteImport.update({
  id: '/regolamento',
  path: '/regolamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificaRoute = ClassificaRouteImport.update({
  id: '/classifica',
  path: '/classifica',
  getParentRoute: () => rootRouteImport,
} as any)
const BallottaggioRoute = BallottaggioRouteImport.update({
  id: '/ballottaggio',
  path: '/ballottaggio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsRoute = ApiTeamsRouteImport.update({
  id: '/api/teams',
  path: '/api/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResultsRoute = ApiResultsRouteImport.update({
  id: '/api/results',
  path: '/api/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassificaDataRoute = ApiClassificaDataRouteImport.update({
  id: '/api/classifica-data',
  path: '/api/classifica-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ballottaggio': typeof BallottaggioRoute
  '/classifica': typeof ClassificaRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/regolamento': typeof RegolamentoRoute
  '/squadra': typeof SquadraRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/classifica-data': typeof ApiClassificaDataRoute
  '/api/results': typeof ApiResultsRoute
  '/api/teams': typeof ApiTeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ballottaggio': typeof BallottaggioRoute
  '/classifica': typeof ClassificaRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/regolamento': typeof RegolamentoRoute
  '/squadra': typeof SquadraRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/classifica-data': typeof ApiClassificaDataRoute
  '/api/results': typeof ApiResultsRoute
  '/api/teams': typeof ApiTeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ballottaggio': typeof BallottaggioRoute
  '/classifica': typeof ClassificaRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/regolamento': typeof RegolamentoRoute
  '/squadra': typeof SquadraRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/classifica-data': typeof ApiClassificaDataRoute
  '/api/results': typeof ApiResultsRoute
  '/api/teams': typeof ApiTeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ballottaggio'
    | '/classifica'
    | '/live'
    | '/login'
    | '/regolamento'
    | '/squadra'
    | '/api/admin'
    | '/api/classifica-data'
    | '/api/results'
    | '/api/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ballottaggio'
    | '/classifica'
    | '/live'
    | '/login'
    | '/regolamento'
    | '/squadra'
    | '/api/admin'
    | '/api/classifica-data'
    | '/api/results'
    | '/api/teams'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ballottaggio'
    | '/classifica'
    | '/live'
    | '/login'
    | '/regolamento'
    | '/squadra'
    | '/api/admin'
    | '/api/classifica-data'
    | '/api/results'
    | '/api/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BallottaggioRoute: typeof BallottaggioRoute
  ClassificaRoute: typeof ClassificaRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  RegolamentoRoute: typeof RegolamentoRoute
  SquadraRoute: typeof SquadraRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiClassificaDataRoute: typeof ApiClassificaDataRoute
  ApiResultsRoute: typeof ApiResultsRoute
  ApiTeamsRoute: typeof ApiTeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/squadra': {
      id: '/squadra'
      path: '/squadra'
      fullPath: '/squadra'
      preLoaderRoute: typeof SquadraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regolamento': {
      id: '/regolamento'
      path: '/regolamento'
      fullPath: '/regolamento'
      preLoaderRoute: typeof RegolamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifica': {
      id: '/classifica'
      path: '/classifica'
      fullPath: '/classifica'
      preLoaderRoute: typeof ClassificaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ballottaggio': {
      id: '/ballottaggio'
      path: '/ballottaggio'
      fullPath: '/ballottaggio'
      preLoaderRoute: typeof BallottaggioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams': {
      id: '/api/teams'
      path: '/api/teams'
      fullPath: '/api/teams'
      preLoaderRoute: typeof ApiTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/results': {
      id: '/api/results'
      path: '/api/results'
      fullPath: '/api/results'
      preLoaderRoute: typeof ApiResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classifica-data': {
      id: '/api/classifica-data'
      path: '/api/classifica-data'
      fullPath: '/api/classifica-data'
      preLoaderRoute: typeof ApiClassificaDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BallottaggioRoute: BallottaggioRoute,
  ClassificaRoute: ClassificaRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  RegolamentoRoute: RegolamentoRoute,
  SquadraRoute: SquadraRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiClassificaDataRoute: ApiClassificaDataRoute,
  ApiResultsRoute: ApiResultsRoute,
  ApiTeamsRoute: ApiTeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
